branch-defaults:
  master:
    environment: flaskr-env
global:
  application_name: flaskr
  default_ec2_keyname: ubuntu-key-pair-20160308
  default_platform: Python 3.4
  default_region: ap-northeast-1
  profile: default
  sc: git
